### ISSUE TITLE
Script Postgres table creation

### ISSUE THREAD

**Issue by greenmoss** [Doveps/old_savant#3]
Goal: a new Postgres script in this repository creates a new, empty set of tables in your Postgres database

Start a new branch to do this work. Remove all files from it.

We don't yet know the exact table structure. Start simple with the following tables: import, flavor, ansible.

This will support https://github.com/Doveps/Architecture/wiki/Demo

**Comment by JosiahRegencia** [comment]
pushed the code to repository savant branch django2.0

I'm not certain about the entities of each table yet. But I put an ID and another entity for the inputs. Far from being normalized.
